# Generated by Django 5.0.4 on 2024-07-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='maps_link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
