# Generated by Django 5.0.4 on 2024-07-17 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_menu_maps_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='qr_code',
        ),
    ]
