# Generated by Django 5.0.4 on 2024-07-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_menu_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='resturaunt_name',
            field=models.CharField(default='Resturaunt', max_length=100),
        ),
    ]
