# Generated by Django 5.0.4 on 2024-07-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_menu_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='template',
            field=models.CharField(default='basic', max_length=100),
        ),
    ]
