# Generated by Django 5.0.7 on 2024-07-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_languages_menu_languages_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='rtl',
            field=models.BooleanField(default=False),
        ),
    ]
