# Generated by Django 5.0.7 on 2024-07-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_item_ingredients_alter_item_ingredients_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='static/uploads/'),
        ),
    ]
