# Generated by Django 5.0.7 on 2024-07-25 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='item',
            name='featured_label',
        ),
        migrations.RemoveField(
            model_name='item',
            name='featured_label_ar',
        ),
        migrations.RemoveField(
            model_name='item',
            name='featured_label_color',
        ),
        migrations.RemoveField(
            model_name='item',
            name='featured_label_de',
        ),
        migrations.RemoveField(
            model_name='item',
            name='featured_label_en',
        ),
        migrations.RemoveField(
            model_name='item',
            name='featured_label_es',
        ),
        migrations.RemoveField(
            model_name='item',
            name='featured_label_fr',
        ),
        migrations.RemoveField(
            model_name='item',
            name='featured_label_ru',
        ),
        migrations.AddField(
            model_name='item',
            name='combo',
            field=models.BooleanField(default=False, help_text='Does the item come with a side & drink?'),
        ),
        migrations.AddField(
            model_name='item',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Do you want to do a sale? This will be the price before discount.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='group',
            field=models.BooleanField(default=False, help_text='Is this item suitable for more than 1 person?'),
        ),
        migrations.AddField(
            model_name='item',
            name='vegan',
            field=models.BooleanField(default=False, help_text='Can this item be eaten by vegeterians?'),
        ),
        migrations.AddField(
            model_name='menu',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='The thumbnail image of the menu.', upload_to='static/uploads/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='The image of the category.', upload_to='static/uploads/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='menu',
            field=models.ForeignKey(help_text='The menu that the category belongs to.', on_delete=django.db.models.deletion.CASCADE, to='main.menu'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(help_text='The title of the category.', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_ar',
            field=models.CharField(help_text='The title of the category.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_de',
            field=models.CharField(help_text='The title of the category.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_en',
            field=models.CharField(help_text='The title of the category.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_es',
            field=models.CharField(help_text='The title of the category.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_fr',
            field=models.CharField(help_text='The title of the category.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_ru',
            field=models.CharField(help_text='The title of the category.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(help_text='The category that the item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(help_text='The image of the item.', upload_to='static/uploads/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='ingredients',
            field=models.TextField(blank=True, help_text='The ingredients of the item.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='ingredients_ar',
            field=models.TextField(blank=True, help_text='The ingredients of the item.', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='ingredients_de',
            field=models.TextField(blank=True, help_text='The ingredients of the item.', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='ingredients_en',
            field=models.TextField(blank=True, help_text='The ingredients of the item.', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='ingredients_es',
            field=models.TextField(blank=True, help_text='The ingredients of the item.', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='ingredients_fr',
            field=models.TextField(blank=True, help_text='The ingredients of the item.', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='ingredients_ru',
            field=models.TextField(blank=True, help_text='The ingredients of the item.', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='menu',
            field=models.ForeignKey(help_text='The menu that the item belongs to.', on_delete=django.db.models.deletion.CASCADE, to='main.menu'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='The price of the item.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(help_text='The title of the item.', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_ar',
            field=models.CharField(help_text='The title of the item.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_de',
            field=models.CharField(help_text='The title of the item.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_en',
            field=models.CharField(help_text='The title of the item.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_es',
            field=models.CharField(help_text='The title of the item.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_fr',
            field=models.CharField(help_text='The title of the item.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_ru',
            field=models.CharField(help_text='The title of the item.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(help_text='The code of the language.', max_length=2),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='The name of the language.', max_length=100),
        ),
        migrations.AlterField(
            model_name='language',
            name='rtl',
            field=models.BooleanField(default=False, help_text='Whether the language is right-to-left.'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='address',
            field=models.CharField(help_text='The address of the restaurant.', max_length=100),
        ),
        migrations.AlterField(
            model_name='menu',
            name='address_ar',
            field=models.CharField(help_text='The address of the restaurant.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='address_de',
            field=models.CharField(help_text='The address of the restaurant.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='address_en',
            field=models.CharField(help_text='The address of the restaurant.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='address_es',
            field=models.CharField(help_text='The address of the restaurant.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='address_fr',
            field=models.CharField(help_text='The address of the restaurant.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='address_ru',
            field=models.CharField(help_text='The address of the restaurant.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='currency',
            field=models.CharField(default='EUR', help_text='The currency used for pricing.', max_length=10),
        ),
        migrations.AlterField(
            model_name='menu',
            name='languages_allowed',
            field=models.ManyToManyField(help_text='The languages allowed for the menu.', to='main.language'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='logo',
            field=models.ImageField(help_text='The logo image of the menu.', upload_to='static/uploads/'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='maps_link',
            field=models.CharField(blank=True, help_text="The link to the restaurant's location on maps.", max_length=100),
        ),
        migrations.AlterField(
            model_name='menu',
            name='phone',
            field=models.CharField(help_text='The phone number of the restaurant.', max_length=100),
        ),
        migrations.AlterField(
            model_name='menu',
            name='resturaunt_name',
            field=models.CharField(default='Resturaunt', help_text='The name of the restaurant.', max_length=100),
        ),
        migrations.AlterField(
            model_name='menu',
            name='template',
            field=models.CharField(default='basic', help_text='The template used for the menu.', max_length=100),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(help_text='The title of the menu.', max_length=100),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title_ar',
            field=models.CharField(help_text='The title of the menu.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title_de',
            field=models.CharField(help_text='The title of the menu.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title_en',
            field=models.CharField(help_text='The title of the menu.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title_es',
            field=models.CharField(help_text='The title of the menu.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title_fr',
            field=models.CharField(help_text='The title of the menu.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title_ru',
            field=models.CharField(help_text='The title of the menu.', max_length=100, null=True),
        ),
    ]
