# Generated by Django 5.0.7 on 2024-07-26 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_item_featured_remove_item_featured_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
