# Generated by Django 5.0.7 on 2024-07-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='template',
            field=models.CharField(choices=[], default='basic', help_text='The template used for the menu.', max_length=100),
        ),
    ]
