# Generated by Django 5.0.7 on 2024-07-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_menu_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='template',
            field=models.CharField(choices=[('basic', 'basic')], default='basic', help_text='The template used for the menu.', max_length=100),
        ),
    ]
