# Generated by Django 5.0.7 on 2024-07-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_menu_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, help_text='The image of the item.', upload_to='static/uploads/'),
        ),
    ]
