# Generated by Django 5.0.7 on 2024-07-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, help_text='The thumbnail image.', upload_to='static/uploads/')),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='menu',
            name='thumbnails',
            field=models.ManyToManyField(blank=True, to='main.thumbnail'),
        ),
    ]
